name: Env file to JSON
description: >
  Source a file and export selected env variables as JSON

inputs:
  source:
    required: true

outputs:
  json:
    value: ${{ steps.collect.outputs.json }}

runs:
  using: composite
  steps:
    - id: collect
      name: Parse simple env file values as JSON
      shell: bash
      run: |
        # Iterate lines in file, no trimming around =
        trap 'echo >&2 E$? L$LINENO' ERR

        json='{}'

        while IFS= read -r line || [[ -n "$line" ]]; do
          line="${line#"${line%%[![:space:]]*}"}"
          line="${line%"${line##*[![:space:]]}"}"

          [[ -z "$line" || "$line" =~ ^# ]] && continue

          [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]
          key="${BASH_REMATCH[1]}"
          value="${BASH_REMATCH[2]}"

          json=$(jq --arg k "${key,,}" --arg v "$value" \
            '. + {($k): $v}' <<< "$json")
        done < "${{ inputs.source }}"

        tee -a "$GITHUB_OUTPUT" >&2 <<< "json=$(jq -c . <<< "$json")"
