name: Env file to JSON
description: Source a file and export selected env vnames as JSON

inputs:
  source-file:
    required: true

  variable-names:
    required: true
    description: Space-separated list of env var names to export

outputs:
  json:
    value: ${{ steps.collect.outputs.json }}

runs:
  using: composite
  steps:
    - id: collect
      name: Collect sourced shell variables as JSON
      shell: bash
      run: |
        # Source shell file, build JSON representation of select variables
        trap 'echo >&2 E$? L$LINENO' ERR      
        source "${{ inputs.source-file }}"

        json='{}'
        for var in ${{ inputs.variable-names }}; do
          json=$(jq --arg k "${var,,}" --arg v "${!var}" \
            '. + {($k): $v}' <<< "$json")
        done

        cat >(tee /dev/stderr >> "$GITHUB_OUTPUT") \
          <<< "json=$(jq -c . <<< "$json")"
