name: Fetch (sub)tree from artifact tar

inputs:
  artifact:
    description: "Artifact name"
    required: true
  target:
    description: "Target directory path to extract to"
    required: true
  prefix:
    description: "Prefix path inside archive to strip out"
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v8
      with:
        name: ${{ inputs.artifact }}
        path: .
    - name: Extract payload or its part
      env:
        ARTIFACT: ${{ inputs.artifact }}
        TARGET: ${{ inputs.target }}
        PREFIX: ${{ inputs.prefix }}
      shell: bash
      run: |
        # Extract tree from artifact into path, optionally strip out subtree only
        # Ensure single tarball named <artifact>.*.tar only
        trap 'echo >&2 E$? L$LINENO' ERR      
        : "${ARTIFACT:?}" "${TARGET:?}"

        found=( "$ARTIFACT".*.tar )
        (( ${#found[@]} == 1 ))
        archive_tar="${found[0]}"
      
        declare -a tar_args=()

        if [[ -n "$PREFIX" ]]; then
          IFS='/' read -r -a parts <<< "$PREFIX"
          tar_args+=(--strip-components=${#parts[@]} "$PREFIX")
        fi

        test ! -e "$TARGET"
        mkdir -p "$TARGET"

        tar -x -C "$TARGET" -f "$archive_tar" "${tar_args[@]}"
