name: Tree from artifact tar
description: >
  Populate tree or its subtree (optional prefix) from artifact tar

inputs:
  artifact:
    description: "Artifact name"
    required: true
  target:
    description: "Target directory path to extract to"
    required: false
    default: ''
  prefix:
    description: "Prefix path inside archive to strip out"
    required: false
    default: ''

outputs:
  target-path:
    value: ${{ steps.unarchive.outputs.path }}

runs:
  using: composite
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v8
      with:
        name: ${{ inputs.artifact }}

    - id: unarchive
      name: Extract payload or its part
      env:
        ARTIFACT: ${{ inputs.artifact }}
        TARGET: ${{ inputs.target }}
        PREFIX: ${{ inputs.prefix }}
      shell: bash
      run: |
        # Extract tree from artifact into path, optionally strip out subtree only
        # Ensure single tarball named <artifact>.*.tar only
        trap 'echo >&2 E$? L$LINENO' ERR      
        : "${ARTIFACT:?}"
      
        test -f "$ARTIFACT"

        [[ -z "$TARGET" ]] || test ! -e "$TARGET"
        [[ -n "$TARGET" ]] || TARGET="$(mktemp -d "/tmp/${ARTIFACT}.XXXXXX")"
        mkdir -p "$TARGET"

        declare -a tar_args=()

        if [[ -n "$PREFIX" ]]; then
          IFS='/' read -r -a parts <<< "$PREFIX"
          tar_args+=(--strip-components=${#parts[@]} "$PREFIX")
        fi

        tar -x -C "$TARGET" -f "$ARTIFACT" "${tar_args[@]}"

        tee -a "$GITHUB_OUTPUT" >&2 << EOF
        path=$TARGET
        EOF
