name: Create source archive from GIT repository
description: Fetch commit, set files mtime to commit timestamp and create a tar archive

inputs:
  git-url:
    description: "GIT Repository URL"
    required: true
  git-ref:
    description: "GIT Ref to fetch"
    required: true
  name:
    description: "Archive name"
    required: true
  permsrc:
    description: "Apply .permsrc"
    required: false
    default: "false"
  upload:
    description: "Upload as artifact"
    required: false
    default: "true"

outputs:
  git-commit-sha:
    value: ${{ steps.archive.outputs.git-commit-sha }}

runs:
  using: "composite"
  steps:
    - id: archive
      name: Fetch repository and create archive
      shell: bash
      run: |
        NAME="${{ inputs.name }}"

        GIT_DIR="$NAME".git
        ARCHIVE_DIR="$NAME"
        ARCHIVE_TAR="$NAME".tar

        [[ ! -e "$GIT_DIR" ]]
        [[ ! -e "$ARCHIVE_DIR" ]]
        [[ ! -e "ARCHIVE_TAR" ]]

        mkdir -p "$GIT_DIR"
        git clone --bare --depth 1 "${{ inputs.git-url }}" "$GIT_DIR"

        export GIT_DIR
        git fetch --depth=1 origin "${{ inputs.git-ref }}"

        COMMIT_SHA=$(git rev-parse FETCH_HEAD)
        COMMIT_ETSTAMP=$(git log -1 --format=%ct "$COMMIT_SHA")

        mkdir -p "$ARCHIVE_DIR"
        git archive --format=tar "$COMMIT_SHA" | tar -C "$ARCHIVE_DIR" -xf -

        [[ "${{ inputs.permsrc }}" == "true" ]] \
          && (cd "$ARCHIVE_DIR" && source .permsrc || exit 1)

        tar --mtime="@${COMMIT_ETSTAMP}" --clamp-mtime -cf "$ARCHIVE_TAR" "$ARCHIVE_DIR"

        cat >> $GITHUB_OUTPUT << EOF
        git-commit-sha=$COMMIT_SHA
        archive-tar=$ARCHIVE_TAR
        EOF

    - name: Upload artifact
      if: ${{ inputs.upload == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.archive.outputs.archive-tar }}
        path: ${{ steps.archive.outputs.archive-tar }}
