name: Create source archive from GIT repository
description: Fetch commit, set files mtime to commit timestamp and create a tar archive

inputs:
  git-url:
    description: "Repository URL"
    required: true
  git-ref:
    description: "Commit SHA or branch to checkout"
    required: true
  name:
    description: "Directory to emit the repo and archive"
    required: true
  permsrc:
    description: "Apply .permsrc"
    required: false
    default: "false"
  upload:
    description: "Upload as artifact"
    required: false
    default: "true"

outputs:
  commit_sha:
    value: ${{ steps.archive.outputs.commit_sha }}

runs:
  using: "composite"
  steps:
    - id: archive
      name: Fetch repository and create archive
      shell: bash
      run: |
        REPO="${{ inputs.git-url }}"
        REF="${{ inputs.git-ref }}"
        DIR="${{ inputs.name }}"
        PERMSRC="${{ inputs.permsrc }}"

        ! [[ -d "$DIR" ]] && ! [[ -d "$DIR".git ]] || exit 1

        mkdir -p "$DIR".git

        git clone --bare --depth 1 "$REPO" "$DIR".git

        export GIT_DIR="$DIR".git
        git fetch --depth=1 origin "$REF"

        COMMIT_SHA=$(git rev-parse FETCH_HEAD)
        COMMIT_ETSTAMP=$(git log -1 --format=%ct "$COMMIT_SHA")

        ARCHIVE_DIR="$DIR"
        mkdir -p "$ARCHIVE_DIR"

        git archive --format=tar "$COMMIT_SHA" | tar -C "$ARCHIVE_DIR" -xf -

        if [[ $PERMSRC == "true" ]]; then
          (
            cd "$ARCHIVE_DIR" \
              && source .permsrc \
              || exit 1
          )
        fi

        tar --mtime="@${COMMIT_ETSTAMP}" --clamp-mtime -cf "$(basename "$DIR").tar" "$ARCHIVE_DIR"

        cat >> $GITHUB_OUTPUT <<< "commit_sha=$COMMIT_SHA"

    - name: Upload artifact
      if: ${{ inputs.upload == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.dir }}-archive
        path: ${{ inputs.dir }}.tar
