name: Source archive
description: Clone at a specific commit and create a tar archive with commit timestamp
inputs:
  repo:
    description: "Repository URL"
    required: true
  ref:
    description: "Commit SHA or branch to checkout"
    required: true
  dir:
    description: "Directory to emit the repo and archive"
    required: true
  permsrc:
    description: "Apply .permsrc"
    required: false
    default: "false"
  upload:
    description: "Upload as artifact"
    required: false
    default: "true"

runs:
  using: "composite"

  steps:
    - name: Ensure target directory does not exist
      shell: bash 
      run: |
        DIR="${{ inputs.dir }}"
        ! [[ -d "$DIR" ]] || {
          echo "Directory '$DIR' already exists. Aborting."
          exit 1
        }

    - name: Checkout repository and create archive
      shell: bash
      run: |
        REPO="${{ inputs.repo }}"
        REF="${{ inputs.ref }}"
        DIR="${{ inputs.dir }}"
        PERMSRC="${{ inputs.permsrc }}"

        mkdir -p "$DIR".git

        git clone --bare --depth 1 "$REPO" "$DIR".git

        export GIT_DIR="$DIR".git
        git fetch --depth=1 origin "$REF"

        COMMIT_SHA=$(git rev-parse FETCH_HEAD)
        COMMIT_ETSTAMP=$(git log -1 --format=%ct "$COMMIT_SHA")

        ARCHIVE_DIR="$DIR"
        mkdir -p "$ARCHIVE_DIR"

        git archive --format=tar "$COMMIT_SHA" | tar -C "$ARCHIVE_DIR" -xf -

        if [[ $PERMSRC == "true" ]]; then
          (
            cd "$ARCHIVE_DIR" \
              && source .permsrc \
              || exit 1
          )
        fi

        tar --mtime="@${COMMIT_ETSTAMP}" --clamp-mtime -cf "$(basename "$DIR").tar" "$ARCHIVE_DIR"

    - name: Upload artifact
      if: ${{ inputs.upload == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.dir }}-archive
        path: ${{ inputs.dir }}.tar
