name: Create source archive from GIT repository
description: Fetch commit, set files mtime to commit timestamp and create a tar archive

inputs:
  git-url:
    description: "GIT Repository URL"
    required: true
  git-ref:
    description: "GIT Ref to fetch"
    required: true
  name:
    description: "Archive name"
    required: true
  permsrc:
    description: "Apply .permsrc"
    required: false
    default: "false"
  upload:
    description: "Upload as artifact"
    required: false
    default: "true"

outputs:
  commit_sha:
    value: ${{ steps.archive.outputs.commit_sha }}

runs:
  using: "composite"
  steps:
    - id: archive
      name: Fetch repository and create archive
      shell: bash
      run: |
        URL="${{ inputs.git-url }}"
        REF="${{ inputs.git-ref }}"
        NAME="${{ inputs.name }}"
        PERMSRC="${{ inputs.permsrc }}"

        GIT_DIR="$NAME".git
        ARCHIVE_DIR="$NAME"

        ! [[ -d "$GIT_DIR" ]] && ! [[ -d "$ARCHIVE_DIR".git ]] || exit 1

        mkdir -p "$GIT_DIR"
        git clone --bare --depth 1 "$URL" "$GIT_DIR"

        export GIT_DIR
        git fetch --depth=1 origin "$REF"

        COMMIT_SHA=$(git rev-parse FETCH_HEAD)
        COMMIT_ETSTAMP=$(git log -1 --format=%ct "$COMMIT_SHA")

        mkdir -p "$ARCHIVE_DIR"
        git archive --format=tar "$COMMIT_SHA" | tar -C "$ARCHIVE_DIR" -xf -

        [[ $PERMSRC == "true" ]] \
          && (cd "$ARCHIVE_DIR" && source .permsrc || exit 1)

        tar --mtime="@${COMMIT_ETSTAMP}" --clamp-mtime -cf "$(basename "$ARCHIVE_DIR").tar" "$ARCHIVE_DIR"

        cat >> $GITHUB_OUTPUT <<< "commit_sha=$COMMIT_SHA"

    - name: Upload artifact
      if: ${{ inputs.upload == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}.tar
        path: ${{ inputs.name }}.tar
