name: Git repo tree
description: Populate tree from git ref, (optional) normalized tar artifact

inputs:
  git-url:
    description: "GIT Repository URL"
    required: true
  git-ref:
    description: "GIT Ref to fetch"
    required: true
  target:
    description: "Directory path to populate"
    required: true
  permsrc:
    description: "Apply .permsrc"
    required: false
    default: "false"
  artifact:
    description: "Artifact name (if to be uploaded)"
    required: false
    default: ''

outputs:
  git-commit:
    value: ${{ steps.archive.outputs.git-commit }}
  archive-tar:
    value: ${{ steps.archive.outputs.archive-tar }}

runs:
  using: "composite"
  steps:
    - id: archive
      name: Fetch repository and create archive
      shell: bash
      env:
        ARCHIVE_DIR: ${{ inputs.target }}
        ARTIFACT_NAME: ${{ inputs.artifact }}
      run: |
        exec 3> >(tee /dev/stderr >> "$GITHUB_OUTPUT")
        trap 'echo >&2 E$? L$LINENO' ERR
        : "${ARCHIVE_DIR:?}"
        
        test ! -e "$ARCHIVE_DIR"
        ARCHIVE_TAR=$(mktemp /tmp/"${ARTIFACT_NAME:-source}".XXXXXX.tar)

        GIT_DIR=$(mktemp -d /tmp/repo.XXXXXX.git)
        git clone --bare --depth 1 "${{ inputs.git-url }}" "$GIT_DIR"
        export GIT_DIR

        git fetch --depth=1 origin "${{ inputs.git-ref }}"
        COMMIT_OID=$(git rev-parse FETCH_HEAD)
        COMMIT_EPOCH=$(git log -1 --format=%ct "$COMMIT_OID")

        git_tar=$(mktemp /tmp/git-archive.XXXXXX.tar)
        git archive --format=tar "$COMMIT_OID" > "$git_tar"

        mkdir -p "$ARCHIVE_DIR"
        tar -C "$ARCHIVE_DIR" -xf "$git_tar"

        if [[ "${{ inputs.permsrc }}" == "true" ]]; then
          pushd "$ARCHIVE_DIR"
          test -f .permsrc
          source .permsrc
          popd
        fi

        tar -C "$ARCHIVE_DIR" \
            --format=gnu --sort=name --owner=0 --group=0 --numeric-owner \
            --mtime="@${COMMIT_EPOCH}" --clamp-mtime -cf "$ARCHIVE_TAR" .

        cat >&3 << EOF
        git-version=$(git --version)
        git-commit=$COMMIT_OID
        archive-tar=$(realpath "$ARCHIVE_TAR")
        EOF

    - name: Upload artifact
      if: ${{ inputs.artifact != '' }}
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.artifact }}
        path: ${{ steps.archive.outputs.archive-tar }}
        include-hidden-files: true
