name: Checkout & Archive Git repository
description: Clone at a specific commit and create a tar archive with commit timestamp
inputs:
  repo:
    description: "Repository URL"
    required: true
  ref:
    description: "Commit SHA or branch to checkout"
    required: true
  dir:
    description: "Directory to emit the repo and archive"
    required: true

runs:
  using: "composite"

  steps:
    - name: Ensure target directory does not exist
      shell: bash 
      run: |
        DIR="${{ inputs.dir }}"
        ! [[ -d "$DIR" ]] || {
          echo "Directory '$DIR' already exists. Aborting."
          exit 1
        }

    - name: Checkout repository and create archive
      shell: bash
      run: |
        REPO="${{ inputs.repo }}"
        REF="${{ inputs.ref }}"
        DIR="${{ inputs.dir }}"

        mkdir -p "$DIR"

        git clone --no-checkout --depth 1 "$REPO" "$DIR"
        cd "$DIR"

        git fetch --depth=1 origin "$REF"

        COMMIT_SHA=$(git rev-parse FETCH_HEAD)

        git checkout "$COMMIT_SHA"

        COMMIT_ETSTAMP=$(git log -1 --format=%ct "$COMMIT_SHA")

        git archive --prefix="$(basename "$DIR")/" --format=tar "$COMMIT_SHA" \
          | tar --mtime="@${COMMIT_ETSTAMP}" -cf $DIR.tar -
