name: Tree from Git ref
description: >
  Populate tree from git reference or commit hash

inputs:
  git-url:
    description: "Git repository URL"
    required: true
  git-ref:
    description: "Reference or object ID to fetch"
    required: true
  target-path:
    description: "Directory path to populate"
    required: false
    default: ''
  permsrc:
    description: "Apply .permsrc flag"
    required: false
    default: "false"

outputs:
  path:
    value: ${{ steps.checkout.outputs.path }}
  git-commit:
    value: ${{ steps.checkout.outputs.git-commit }}
  git-commit-epoch:
    value: ${{ steps.checkout.outputs.git-commit-epoch }}

runs:
  using: composite
  steps:
    - id: checkout
      name: Fetch commit tree for given ref
      shell: bash
      env:
        GIT_URL: ${{ inputs.git-url }}
        GIT_REF: ${{ inputs.git-ref }}
        TARGET: ${{ inputs.target-path }}
      run: |
        # Clone bare repo, fetch ref, populate tree into path
        trap 'echo >&2 E$? L$LINENO' ERR
        : "${GIT_URL:?}" "${GIT_REF:?}"
        [[ -z "$TARGET" ]] || test ! -e "$TARGET"
        [[ -n "$TARGET" ]] || TARGET="$(mktemp -d /tmp/tree.XXXXXX)"

        mkdir -p "$TARGET"

        export GIT_ADVICE=0
        GIT_DIR=$(mktemp -d "/tmp/source.XXXXXX.git")
        git init --bare "$GIT_DIR"
        export GIT_DIR
        export GIT_WORK_TREE="$TARGET"

        git fetch --depth=1 "$GIT_URL" "$GIT_REF"
        COMMIT_OID=$(git rev-parse FETCH_HEAD)
        COMMIT_EPOCH=$(git show -s --format=%ct "$COMMIT_OID")
        git checkout -f "$COMMIT_OID"

        tee -a "$GITHUB_OUTPUT" >&2 << EOF
        path=$TARGET        
        git-commit=$COMMIT_OID
        git-commit-epoch=$COMMIT_EPOCH
        EOF

    - id: perms
      name: Apply permissions
      if: ${{ inputs.permsrc == 'true' }}      
      shell: bash
      env:
        TARGET: ${{ steps.checkout.outputs.path }}
      run: |
        # Source .permsrc
        ls -la /tmp
        cd "$TARGET"
        source .permsrc
