name: Tree from Git ref
description: >
  Populate tree from git reference or commit hash

inputs:
  git-url:
    description: "Repository URL"
    required: true
  git-ref:
    description: "Reference to fetch"
    required: true
  target-path:
    description: "Directory path to populate"
    required: false
    default: ''
  artifact:
    description: "Upload archive as artifact"
    required: false
    default: true

outputs:
  git-commit:
    value: ${{ steps.archive.outputs.git-commit }}
  git-commit-epoch:
    value: ${{ steps.archive.outputs.git-commit-epoch }}
  path:
    value: ${{ steps.target.outputs.path }}
  artifact-id:
    value: ${{ steps.artifact.artifact-id }}

runs:
  using: composite
  steps:
    - id: archive
      name: Obtain tree archive for given ref
      shell: bash
      env:
        GIT_URL: ${{ inputs.git-url }}
        GIT_REF: ${{ inputs.git-ref }}
      run: |
        # Create bare repo, fetch commit, create archive
        trap 'echo >&2 E$? L$LINENO' ERR        
        : "${GIT_URL:?} ${GIT_REF:?}"

        GIT_DIR=$(mktemp -d "/tmp/repo.XXXXXX.git")

        export GIT_ADVICE=0
        git init --bare "$GIT_DIR"
        export GIT_DIR

        git fetch --depth=1 "$GIT_URL" "$GIT_REF"
        COMMIT_OID=$(git rev-parse FETCH_HEAD)
        COMMIT_EPOCH=$(git show -s --format=%ct "$COMMIT_OID")

        ARCHIVE="$(mktemp "/tmp/archive-${COMMIT_OID}.XXXXXX.tar")"
        git archive --format=tar "$COMMIT_OID" > "$ARCHIVE"

        tee -a "$GITHUB_OUTPUT" >&2 << EOF
        path=$ARCHIVE
        git-commit=$COMMIT_OID
        git-commit-epoch=$COMMIT_EPOCH
        EOF

    - id: target
      name: Populate tree from archive
      shell: bash
      env:
        COMMIT: ${{ steps.archive.outputs.git-commit }}
        ARCHIVE: ${{ steps.archive.outputs.path }}
        TARGET: ${{ inputs.target-path }}
      run: |
        # Untar to specified or generic directory
        trap 'echo >&2 E$? L$LINENO' ERR
        : "${COMMIT:?} ${ARCHIVE:?}"
        
        [[ -z "$TARGET" ]] || test ! -e "$TARGET"
        [[ -n "$TARGET" ]] || TARGET="$(mktemp -d "/tmp/commit-${COMMIT}.XXXXXX")"

        mkdir -p "$TARGET"
        tar -xf "$ARCHIVE" -C "$TARGET"

        tee -a "$GITHUB_OUTPUT" >&2 << EOF
        path=$TARGET
        EOF

    - id: artifact
      name: Upload artifact
      if: ${{ inputs.artifact == 'true' }}
      uses: actions/upload-artifact@v7
      with:
        path: ${{ steps.archive.outputs.path }}
        archive: false
        include-hidden-files: true
        retention-days: 1
