name: Prep source and environment

runs:
  using: composite
  steps:
    - name: Download kit archive
      uses: actions/download-artifact@v4
      with:
        name: kit-archive
        path: .
    - name: Download source archive
      uses: actions/download-artifact@v4
      with:
        name: gitrepo-archive
        path: .
    - name: Extract archives
      shell: bash
      run: |
        tar -xf kit.tar
        tar -xf gitrepo.tar
    - name: Download environment
      uses: actions/download-artifact@v4
      with:
        name: prep-env-dir
        path: ./env
