name: Fetch archive
description: >
  Download archive artifact, extract it into temp directory (default)

inputs:
  name:
    description: "Artifact name"
    required: true
  extract:
    description: "Extract locally"
    required: false
    default: true

outputs:
  archive-path:
    value: ${{ steps.artifact.outputs.download-path }}/${{ inputs.name }}  
  extract-path:
    value: ${{ steps.extract.outputs.path }}

runs:
  using: composite
  steps:
    - id: artifact
      name: Download artifact
      uses: actions/download-artifact@v8
      with:
        name: ${{ inputs.name }}
        skip-decompress: true

    - id: extract
      name: Extract archive
      if: ${{ inputs.extract == 'true' }}
      env:
        ARCHIVE: ${{ steps.artifact.outputs.download-path }}/${{ inputs.name }}
      shell: bash
      run: |
        # Extract tree from archive into a temp dir
        : "${ARCHIVE:?}"
      
        test -f "$ARCHIVE"

        TARGET=$(mktemp -d --tmpdir "${ARCHIVE##*/}.XXXXXX")
        tar --extract --file "$ARCHIVE" --directory "$TARGET"

        >&2 echo "::group::output"
        >&2 tee -a "$GITHUB_OUTPUT" << EOF
        >&2 echo "::endgroup:"
        path=$TARGET
        EOF
