name: Fetch artifact tar

inputs:
  artifact:
    description: "Artifact name"
    required: true
  target:
    description: "Target path to extract to"
    required: true
  prefix:
    description: "Prefix path inside archive to strip out"
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Download archive
      uses: actions/download-artifact@v8
      with:
        name: ${{ inputs.artifact }}
        path: .
    - name: Extract (prefixed) payload
      env:
        ARTIFACT: ${{ inputs.artifact }}
        TARGET: ${{ inputs.target }}
        PREFIX: ${{ inputs.prefix }}
      shell: bash
      run: |
        tars=( "$ARTIFACT".*.tar )
        (( ${#tars[@]} == 1 ))
        archive_tar="${tars[0]}"
      
        declare -a tar_args=()

        if [[ -n "$PREFIX" ]]; then
          IFS='/' read -r -a parts <<< "$PREFIX"
          tar_args+=(--strip-components=${#parts[@]} "$PREFIX")
        fi

        test ! -e  "$TARGET"
        mkdir -p "$TARGET"

        tar -x -C "$TARGET" -f "$archive_tar" "${tar_args[@]}"
