name: Fetch artifact tar

inputs:
  name:
    description: "Artifact name"
    required: true
  prefix:
    description: "Prefix inside archive"
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Download archive
      uses: actions/download-artifact@v8
      with:
        name: ${{ inputs.name }}
        path: .
    - name: Extract archives
      env:
        NAME: ${{ inputs.name }}
        PREFIX: ${{ inputs.prefix }}
      shell: bash
      run: |
        test ! -e  "$NAME"
        mkdir -p "$NAME"
        tar -C "$NAME" -xf "$NAME.tar" "${PREFIX:-.}"
