name: Verify build - plain
description: >
  Run build inside container, verify integrity & expected checksum

inputs:
  image:
    description: Container image to run
    required: true
  source-dir:
    description: Source directory on host
    required: true
  source-date-epoch:
    required: true
  compressor:
    required: true
  package:
    required: true
  version:
    required: true
  sha256:
    required: true

outputs:
  status:
    value: ${{ steps.verify.outputs.status }}

runs:
  using: composite
  steps:
    - id: build
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
        SRCDIR: ${{ inputs.source-dir }}/${{ inputs.package }}
        SOURCE_DATE_EPOCH: ${{ inputs.source-date-epoch }}
        DPKG_DEB_COMPRESSOR_TYPE: ${{ inputs.compressor }}
      run: |
        : "${IMAGE:?} ${SRCDIR:?}"

        OUTDIR="$(mktemp -d --tmpdir podman-run-out.XXXXXX)"

        podman run --rm \
          --userns=keep-id \
          --network=none \
          -v "$SRCDIR":/mnt/src:ro \
          -v "$OUTDIR":/mnt/out \
          -v "${{ github.action_path }}/build.sh":/mnt/build.sh:ro \
          -e SOURCE_DATE_EPOCH \
          -e DPKG_DEB_COMPRESSOR_TYPE \
          "$IMAGE" \
          /mnt/build.sh "/mnt/src/" "/mnt/out/built.deb"
        
        >&2 tee -a "$GITHUB_OUTPUT" << EOF
        built-deb=$OUTDIR/built.deb
        EOF

    - id: verify
      shell: bash
      env:
        PACKAGE: ${{ inputs.package }}
        VERSION: ${{ inputs.version }}
        SHA256: ${{ inputs.sha256 }}
        BUILT_DEB: ${{ steps.build.outputs.built-deb }}
      run: |
        : "${PACKAGE:?} ${VERSION:?} ${SHA256:?} ${BUILT_DEB}"

        test -f "$BUILT_DEB"

        echo "::group::contents"
        dpkg-deb --contents "$BUILT_DEB"
        echo "::endgroup::"

        built="$(dpkg-deb --show --showformat='${Package}|${Version}' "$BUILT_DEB")"
        [[ "$built" == "$PACKAGE|$VERSION" ]]

        sha256sum --check <<< "$SHA256  $BUILT_DEB"

        >&2 tee -a "$GITHUB_OUTPUT" << EOF
        status=pass
        EOF
