name: APT satisfy
description: >
  APT satisfy set of packages on the runner under sanitised config

inputs:
  expression:
    required: true
    description: "apt satisfy expression"

runs:
  using: composite
  env:
    OVERRIDE_APT_CONF: ${{ github.action_path }}/override.apt.conf
  steps:
    - name: Install apt packages
      shell: bash
      run: |
        export APT_CONFIG="$(realpath "$OVERRIDE_APT_CONF")"
        export DEBIAN_FRONTEND=noninteractive

        sudo -E apt-get update
        sudo -E apt-get satisfy ${{ inputs.expression }}
