name: Git archive artifact
description: >
  Create archive from git repository, upload as artifact (default),
  extract locally (optional)

inputs:
  git-repo:
    description: "Git repository"
    required: true
  git-ref:
    description: "Git reference"
    required: true
  base-name:
    description: "Prefix for filename (optional)"
    required: false
    default: 'git-archive'
  upload:
    description: "Upload archive as artifact (default)"
    required: false
    default: true
  extract:
    description: "Extract locally"
    required: false
    default: false

outputs:
  name:
    value: ${{ steps.archive.outputs.name }}
  path:
    value: ${{ steps.extract.outputs.path }}
  git-commit:
    value: ${{ steps.archive.outputs.git-commit }}
  git-commit-epoch:
    value: ${{ steps.archive.outputs.git-commit-epoch }}

runs:
  using: composite
  steps:
    - id: archive
      name: Create git archive
      shell: bash
      env:
        GIT_REPO: ${{ inputs.git-repo }}
        GIT_REF: ${{ inputs.git-ref }}
        BASENAME: ${{ inputs.base-name }}
      run: |
        # Create bare repo, fetch commit, create archive

        : "${GIT_REPO:?} ${GIT_REF:?}"

        [[ "$BASENAME" =~ ^[a-zA-Z0-9._-]+$ ]]

        GIT_DIR=$(mktemp -d "/tmp/repo.XXXXXX.git")

        export GIT_ADVICE=0
        git init --bare "$GIT_DIR"
        export GIT_DIR

        git fetch --depth=1 "$GIT_REPO" "$GIT_REF"
        COMMIT_OID=$(git rev-parse FETCH_HEAD)
        COMMIT_EPOCH=$(git show -s --format=%ct "$COMMIT_OID")

        ARCHIVE=$(mktemp --tmpdir --suffix=.tar "${BASENAME}-${COMMIT_OID}.XXXXXX")
        git archive --format=tar "$COMMIT_OID" > "$ARCHIVE"

        >&2 echo "-- OUTPUT"
        >&2 tee -a "$GITHUB_OUTPUT" << EOF
        path=$ARCHIVE
        name=${ARCHIVE##*/}
        git-commit=$COMMIT_OID
        git-commit-epoch=$COMMIT_EPOCH
        EOF

    - id: artifact
      name: Upload artifact
      if: ${{ inputs.upload == 'true' }}
      uses: actions/upload-artifact@v7
      with:
        path: ${{ steps.archive.outputs.path }}
        archive: false
        include-hidden-files: true
        retention-days: 1

    - id: extract
      name: Populate tree from archive
      if: ${{ inputs.extract == 'true' }}
      shell: bash
      env:
        COMMIT: ${{ steps.archive.outputs.git-commit }}
        ARCHIVE: ${{ steps.archive.outputs.path }}
      run: |
        # Untar to temp directory

        : "${COMMIT:?} ${ARCHIVE:?}"

        TARGET=$(mktemp -d --tmpdir "${ARCHIVE##*/}.XXXXXX")

        tar --extract --file "$ARCHIVE" --directory "$TARGET"

        >&2 echo "-- OUTPUT"
        >&2 tee -a "$GITHUB_OUTPUT" << EOF
        path=$TARGET
        EOF
