name: Tree from Git ref
description: Populate tree from git ref, create normalized archive; upload as artifact (optional)

inputs:
  git-url:
    description: "Git repo URL"
    required: true
  git-ref:
    description: "Git ref to fetch"
    required: true
  target:
    description: "Directory path to populate"
    required: true
  permsrc:
    description: "Apply .permsrc"
    required: false
    default: "false"
  artifact:
    description: "Artifact name (if to be uploaded)"
    required: false
    default: ''

outputs:
  git-commit:
    value: ${{ steps.checkout.outputs.git-commit }}
  git-commit-epoch:
    value: ${{ steps.checkout.outputs.git-commit-epoch }}
  tar-path:
    value: ${{ steps.archive.outputs.tar-path }}
  tar-sha256:
    value: ${{ steps.archive.outputs.tar-sha256 }}

runs:
  using: "composite"
  steps:
    - id: checkout
      name: Fetch commit tree for given ref
      shell: bash
      env:
        GIT_URL: ${{ inputs.git-url }}
        GIT_REF: ${{ inputs.git-ref }}
        TARGET: ${{ inputs.target }}
      run: |
        # Clone bare repo, fetch ref, populate tree into path
        trap 'echo >&2 E$? L$LINENO' ERR
        : "${GIT_URL:?}" "${GIT_REF:?}" "${TARGET:?}"

        test ! -e "$TARGET"
        mkdir -p "$TARGET"

        export GIT_ADVICE=0
        GIT_DIR=$(mktemp -d "/tmp/source.XXXXXX.git")
        git init --bare "$GIT_DIR"
        export GIT_DIR
        export GIT_WORK_TREE="$TARGET"

        git fetch --depth=1 "$GIT_URL" "$GIT_REF"
        COMMIT_OID=$(git rev-parse FETCH_HEAD)
        COMMIT_EPOCH=$(git show -s --format=%ct "$COMMIT_OID")
        git checkout -f "$COMMIT_OID"

        tee -a "$GITHUB_OUTPUT" >&2 << EOF
        git-commit=$COMMIT_OID
        git-commit-epoch=$COMMIT_EPOCH
        EOF

    - id: perms
      name: Apply permissions
      if: ${{ inputs.permsrc == 'true' }}      
      shell: bash
      env:
        TARGET: ${{ inputs.target }}
      run: |
        # Source .permsrc
        cd "$TARGET"
        source .permsrc

    - id: archive
      name: Canonical archive
      shell: bash
      env:
        TARGET: ${{ inputs.target }}
        NAME: ${{ inputs.artifact }}
        EPOCH: ${{ steps.checkout.outputs.git-commit-epoch }}
      run: |
        # Make tarball & calculate its checksum
        [[ -z "$NAME" || "$NAME" =~ ^[a-zA-Z0-9._-]+$ ]]

        TAR=$(mktemp /tmp/"${NAME:-source}".XXXXXX.tar)

        tar -C "$TARGET" \
            --format=gnu --sort=name --owner=0 --group=0 --numeric-owner \
            --mtime="@${EPOCH}" --clamp-mtime -cf "$TAR" .
        read -r TAR_SHA256 _ < <(sha256sum "$TAR")

        tee -a "$GITHUB_OUTPUT" >&2 << EOF
        tar-path=$(realpath "$TAR")
        tar-sha256=$TAR_SHA256
        EOF

    - name: Upload artifact
      if: ${{ inputs.artifact != '' }}
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.artifact }}
        path: ${{ steps.archive.outputs.tar-path }}
        include-hidden-files: true
        retention-days: 1
