name: Fetch archive artifact
description: >
  Populate tree from artifact archive

inputs:
  artifact:
    description: "Artifact name"
    required: true

outputs:
  path:
    value: ${{ steps.extract.outputs.path }}

runs:
  using: composite
  steps:
    - id: artifact
      name: Download artifact
      uses: actions/download-artifact@v8
      with:
        name: ${{ inputs.artifact }}
        skip-decompress: true

    - id: extract
      name: Extract payload or its part
      env:
        ARCHIVE: ${{ steps.artifact.outputs.download-path }}/${{ inputs.artifact }}
      shell: bash
      run: |
        # Extract tree from archive into a temp dir
        : "${ARCHIVE:?}"
      
        test -f "$ARCHIVE"

        TARGET="$(mktemp -d "/tmp/tree.XXXXXX")"

        tar -x -C "$TARGET" -f "$ARCHIVE"

        tee -a "$GITHUB_OUTPUT" >&2 << EOF
        path=$TARGET
        EOF
