name: Tree from artifact archive
description: >
  Populate tree from artifact archive

inputs:
  artifact:
    description: "Artifact name"
    required: true
  target:
    description: "Target directory (optional, must exist)"
    required: false
    default: ''

outputs:
  target-path:
    value: ${{ steps.extract.outputs.path }}

runs:
  using: composite
  steps:
    - id: artifact
      name: Download artifact
      uses: actions/download-artifact@v8
      with:
        name: ${{ inputs.artifact }}
        skip-decompress: true

    - id: extract
      name: Extract payload or its part
      env:
        ARTIFACT: ${{ steps.artifact.outputs.download-path }}/${{ inputs.artifact }}
        TARGET: ${{ inputs.target }}
      shell: bash
      run: |
        # Extract tree from archive into path or new temp dir
        : "${ARTIFACT:?}"
      
        test -f "$ARTIFACT"

        [[ -n "$TARGET" ]] || TARGET="$(mktemp -d "/tmp/tree.XXXXXX")"
        test -d "$TARGET"

        tar -x -C "$TARGET" -f "$ARTIFACT"

        tee -a "$GITHUB_OUTPUT" >&2 << EOF
        path=$TARGET
        EOF
